export const WEB_DIRECTORIES = [
  'public',
  'src/assets',
  'src/enums',
  'src/interfaces',
  'src/models',
  'src/navigation',
  'src/pages',
  'src/services',
  'src/shared/components',
  'src/shared/constants',
  'src/shared/containers',
  'src/shared/contexts',
  'src/shared/data',
  'src/shared/hooks',
  'src/shared/mocks',
  'src/shared/props',
  'src/shared/providers',
  'src/shared/styles',
  'src/shared/utils',
  'src/types',
] as const;
