services:
  db:
    image: postgres:17-alpine

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - '${POSTGRES_PORT:-5433}:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '${API_PORT:-3000}:3000'

    environment:
      PORT: 3000
      NODE_ENV: development

      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      DATABASE_SSL: 'false'
      DATABASE_POOL_MAX: ${DATABASE_POOL_MAX:-2}

      API_BASE_ROUTE: ${API_BASE_ROUTE:-api}
      API_VERSION: ${API_VERSION:-v1}

    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
